In [1]:
import numpy as np 
import pandas as pd
import itertools

In [2]:
df = pd.read_csv('retail.dat.gz',compression='gzip' , sep=',')
df

      0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29
0                                              30 31 32
1                                              33 34 35
2                      36 37 38 39 40 41 42 43 44 45 46
3                                           38 39 47 48
4                38 39 48 49 50 51 52 53 54 55 56 57 58
...                                                  ...
88156    39 875 2665 2962 12959 14070 14406 15518 16379
88157  39 41 101 346 393 413 479 522 586 635 695 799 ...
88158                                         2310 4267
88159                                        39 48 2528
88160                                32 39 205 242 1393

[88161 rows x 1 columns]

In [3]:
df.loc[88161] = df.columns  # adding a row
df = df.rename(columns={df.columns[0] : 'items' })
df

                                                   items
0                                              30 31 32
1                                              33 34 35
2                      36 37 38 39 40 41 42 43 44 45 46
3                                           38 39 47 48
4                38 39 48 49 50 51 52 53 54 55 56 57 58
...                                                  ...
88157  39 41 101 346 393 413 479 522 586 635 695 799 ...
88158                                         2310 4267
88159                                        39 48 2528
88160                                32 39 205 242 1393
88161  0 1 2 3 4 5 6 7 8 9 10 11 12 13 14 15 16 17 18...

[88162 rows x 1 columns]

In [4]:
df['items'] = df['items'].apply(lambda x : x.split(' '))

In [5]:
count_1_item = {}

def count_1 (x) :
    for i in x:
        if i not in count_1_item.keys() : 
            count_1_item[i] = 1
        else :
            count_1_item[i] += 1

df['items'].apply(count_1)

del count_1_item[""]

In [6]:
data = pd.DataFrame()
data['items']  = count_1_item.keys()
data['number']  = count_1_item.values()
data

       items  number
0         30     540
1         31     920
2         32   15167
3         33      37
4         34      14
...      ...     ...
16465  16465       1
16466  16466       1
16467  16467       1
16468  16468       1
16469  16469       1

[16470 rows x 2 columns]

In [7]:
def prunning(df , k ):
    data = data[data['number'] > k ]

In [8]:
def creat_superset(i):
    superset = list(itertools.combinations(data['items'] , i))

In [9]:
superset = list(itertools.combinations(data['items'] , 2))
superset

[('30', '31'),
 ('30', '32'),
 ('30', '33'),
 ('30', '34'),
 ('30', '35'),
 ('30', '36'),
 ('30', '37'),
 ('30', '38'),
 ('30', '39'),
 ('30', '40'),
 ('30', '41'),
 ('30', '42'),
 ('30', '43'),
 ('30', '44'),
 ('30', '45'),
 ('30', '46'),
 ('30', '47'),
 ('30', '48'),
 ('30', '49'),
 ('30', '50'),
 ('30', '51'),
 ('30', '52'),
 ('30', '53'),
 ('30', '54'),
 ('30', '55'),
 ('30', '56'),
 ('30', '57'),
 ('30', '58'),
 ('30', '59'),
 ('30', '60'),
 ('30', '61'),
 ('30', '62'),
 ('30', '3'),
 ('30', '63'),
 ('30', '64'),
 ('30', '65'),
 ('30', '66'),
 ('30', '67'),
 ('30', '68'),
 ('30', '69'),
 ('30', '70'),
 ('30', '71'),
 ('30', '72'),
 ('30', '73'),
 ('30', '74'),
 ('30', '75'),
 ('30', '76'),
 ('30', '77'),
 ('30', '78'),
 ('30', '79'),
 ('30', '80'),
 ('30', '81'),
 ('30', '82'),
 ('30', '83'),
 ('30', '84'),
 ('30', '85'),
 ('30', '86'),
 ('30', '87'),
 ('30', '88'),
 ('30', '89'),
 ('30', '90'),
 ('30', '91'),
 ('30', '92'),
 ('30', '93'),
 ('30', '94'),
 ('30', '95'),
 ('30', '96'),
 ('30', '97'),
 ('30', '98'),
 ('30', '99'),
 ('30', '100'),
 ('30', '101'),
 ('30', '102'),
 ('30', '103'),
 ('30', '104'),
 ('30', '105'),
 ('30', '106'),
 ('30', '107'),
 ('30', '108'),
 ('30', '109'),
 ('30', '110'),
 ('30', '111'),
 ('30', '112'),
 ('30', '113'),
 ('30', '114'),
 ('30', '115'),
 ('30', '116'),
 ('30', '117'),
 ('30', '118'),
 ('30', '119'),
 ('30', '120'),
 ('30', '121'),
 ('30', '122'),
 ('30', '123'),
 ('30', '124'),
 ('30', '125'),
 ('30', '126'),
 ('30', '127'),
 ('30', '128'),
 ('30', '129'),
 ('30', '130'),
 ('30', '131'),
 ('30', '132'),
 ('30', '133'),
 ('30', '134'),
 ('30', '135'),
 ('30', '136'),
 ('30', '137'),
 ('30', '138'),
 ('30', '139'),
 ('30', '140'),
 ('30', '141'),
 ('30', '142'),
 ('30', '143'),
 ('30', '144'),
 ('30', '145'),
 ('30', '146'),
 ('30', '147'),
 ('30', '148'),
 ('30', '149'),
 ('30', '150'),
 ('30', '151'),
 ('30', '152'),
 ('30', '153'),
 ('30', '154'),
 ('30', '155'),
 ('30', '156'),
 ('30', '157'),
 ('30', '158'),
 ('30', '159'),
 ('30', '160'),
 ('30', '161'),
 ('30', '162'),
 ('30', '163'),
 ('30', '164'),
 ('30', '165'),
 ('30', '166'),
 ('30', '167'),
 ('30', '168'),
 ('30', '169'),
 ('30', '170'),
 ('30', '171'),
 ('30', '172'),
 ('30', '173'),
 ('30', '174'),
 ('30', '175'),
 ('30', '176'),
 ('30', '177'),
 ('30', '178'),
 ('30', '179'),
 ('30', '180'),
 ('30', '181'),
 ('30', '182'),
 ('30', '183'),
 ('30', '184'),
 ('30', '185'),
 ('30', '186'),
 ('30', '187'),
 ('30', '188'),
 ('30', '189'),
 ('30', '190'),
 ('30', '191'),
 ('30', '192'),
 ('30', '193'),
 ('30', '194'),
 ('30', '195'),
 ('30', '196'),
 ('30', '197'),
 ('30', '198'),
 ('30', '199'),
 ('30', '200'),
 ('30', '201'),
 ('30', '202'),
 ('30', '203'),
 ('30', '204'),
 ('30', '205'),
 ('30', '206'),
 ('30', '207'),
 ('30', '208'),
 ('30', '209'),
 ('30', '210'),
 ('30', '211'),
 ('30', '212'),
 ('30', '213'),
 ('30', '214'),
 ('30', '215'),
 ('30', '216'),
 ('30', '217'),
 ('30', '218'),
 ('30', '219'),
 ('30', '220'),
 ('30', '221'),
 ('30', '222'),
 ('30', '223'),
 ('30', '224'),
 ('30', '225'),
 ('30', '226'),
 ('30', '227'),
 ('30', '228'),
 ('30', '229'),
 ('30', '230'),
 ('30', '231'),
 ('30', '232'),
 ('30', '233'),
 ('30', '234'),
 ('30', '235'),
 ('30', '236'),
 ('30', '237'),
 ('30', '238'),
 ('30', '239'),
 ('30', '240'),
 ('30', '241'),
 ('30', '242'),
 ('30', '243'),
 ('30', '244'),
 ('30', '245'),
 ('30', '246'),
 ('30', '247'),
 ('30', '248'),
 ('30', '249'),
 ('30', '250'),
 ('30', '251'),
 ('30', '252'),
 ('30', '253'),
 ('30', '254'),
 ('30', '255'),
 ('30', '256'),
 ('30', '257'),
 ('30', '258'),
 ('30', '259'),
 ('30', '260'),
 ('30', '261'),
 ('30', '262'),
 ('30', '263'),
 ('30', '264'),
 ('30', '265'),
 ('30', '266'),
 ('30', '267'),
 ('30', '268'),
 ('30', '269'),
 ('30', '270'),
 ('30', '271'),
 ('30', '272'),
 ('30', '273'),
 ('30', '274'),
 ('30', '275'),
 ('30', '276'),
 ('30', '277'),
 ('30', '278'),
 ('30', '279'),
 ('30', '280'),
 ('30', '281'),
 ('30', '282'),
 ('30', '283'),
 ('30', '284'),
 ('30', '285'),
 ('30', '286'),
 ('30', '287'),
 ('30', '288'),
 ('30', '289'),
 ('30', '290'),
 ('30', '291'),
 ('30', '292'),
 ('30', '293'),
 ('30', '294'),
 ('30', '295'),
 ('30', '296'),
 ('30', '297'),
 ('30', '298'),
 ('30', '299'),
 ('30', '300'),
 ('30', '301'),
 ('30', '302'),
 ('30', '303'),
 ('30', '304'),
 ('30', '305'),
 ('30', '306'),
 ('30', '307'),
 ('30', '308'),
 ('30', '309'),
 ('30', '310'),
 ('30', '311'),
 ('30', '312'),
 ('30', '313'),
 ('30', '314'),
 ('30', '315'),
 ('30', '316'),
 ('30', '317'),
 ('30', '318'),
 ('30', '319'),
 ('30', '320'),
 ('30', '321'),
 ('30', '10'),
 ('30', '322'),
 ('30', '323'),
 ('30', '324'),
 ('30', '325'),
 ('30', '326'),
 ('30', '327'),
 ('30', '328'),
 ('30', '329'),
 ('30', '330'),
 ('30', '331'),
 ('30', '332'),
 ('30', '333'),
 ('30', '334'),
 ('30', '335'),
 ('30', '336'),
 ('30', '337'),
 ('30', '338'),
 ('30', '339'),
 ('30', '18'),
 ('30', '340'),
 ('30', '341'),
 ('30', '342'),
 ('30', '343'),
 ('30', '344'),
 ('30', '345'),
 ('30', '346'),
 ('30', '347'),
 ('30', '348'),
 ('30', '349'),
 ('30', '350'),
 ('30', '351'),
 ('30', '352'),
 ('30', '353'),
 ('30', '354'),
 ('30', '355'),
 ('30', '356'),
 ('30', '357'),
 ('30', '358'),
 ('30', '359'),
 ('30', '360'),
 ('30', '361'),
 ('30', '362'),
 ('30', '363'),
 ('30', '364'),
 ('30', '365'),
 ('30', '366'),
 ('30', '367'),
 ('30', '368'),
 ('30', '369'),
 ('30', '370'),
 ('30', '371'),
 ('30', '372'),
 ('30', '373'),
 ('30', '374'),
 ('30', '375'),
 ('30', '1'),
 ('30', '11'),
 ('30', '376'),
 ('30', '377'),
 ('30', '378'),
 ('30', '379'),
 ('30', '380'),
 ('30', '381'),
 ('30', '382'),
 ('30', '383'),
 ('30', '384'),
 ('30', '385'),
 ('30', '386'),
 ('30', '387'),
 ('30', '388'),
 ('30', '389'),
 ('30', '390'),
 ('30', '391'),
 ('30', '392'),
 ('30', '393'),
 ('30', '394'),
 ('30', '395'),
 ('30', '396'),
 ('30', '397'),
 ('30', '398'),
 ('30', '399'),
 ('30', '400'),
 ('30', '401'),
 ('30', '402'),
 ('30', '403'),
 ('30', '404'),
 ('30', '405'),
 ('30', '406'),
 ('30', '407'),
 ('30', '408'),
 ('30', '409'),
 ('30', '410'),
 ('30', '411'),
 ('30', '412'),
 ('30', '413'),
 ('30', '414'),
 ('30', '415'),
 ('30', '416'),
 ('30', '417'),
 ('30', '418'),
 ('30', '419'),
 ('30', '420'),
 ('30', '421'),
 ('30', '422'),
 ('30', '423'),
 ('30', '424'),
 ('30', '425'),
 ('30', '426'),
 ('30', '427'),
 ('30', '428'),
 ('30', '429'),
 ('30', '430'),
 ('30', '431'),
 ('30', '432'),
 ('30', '433'),
 ('30', '434'),
 ('30', '435'),
 ('30', '436'),
 ('30', '437'),
 ('30', '438'),
 ('30', '15'),
 ('30', '23'),
 ('30', '439'),
 ('30', '440'),
 ('30', '441'),
 ('30', '442'),
 ('30', '443'),
 ('30', '444'),
 ('30', '445'),
 ('30', '446'),
 ('30', '447'),
 ('30', '448'),
 ('30', '449'),
 ('30', '450'),
 ('30', '451'),
 ('30', '452'),
 ('30', '453'),
 ('30', '454'),
 ('30', '455'),
 ('30', '456'),
 ('30', '457'),
 ('30', '458'),
 ('30', '459'),
 ('30', '460'),
 ('30', '461'),
 ('30', '462'),
 ('30', '463'),
 ('30', '464'),
 ('30', '465'),
 ('30', '466'),
 ('30', '467'),
 ('30', '468'),
 ('30', '469'),
 ('30', '470'),
 ('30', '471'),
 ('30', '472'),
 ('30', '473'),
 ('30', '474'),
 ('30', '475'),
 ('30', '476'),
 ('30', '477'),
 ('30', '478'),
 ('30', '479'),
 ('30', '480'),
 ('30', '481'),
 ('30', '482'),
 ('30', '483'),
 ('30', '484'),
 ('30', '485'),
 ('30', '486'),
 ('30', '487'),
 ('30', '488'),
 ('30', '489'),
 ('30', '490'),
 ('30', '491'),
 ('30', '492'),
 ('30', '493'),
 ('30', '494'),
 ('30', '495'),
 ('30', '496'),
 ('30', '497'),
 ('30', '498'),
 ('30', '499'),
 ('30', '500'),
 ('30', '501'),
 ('30', '502'),
 ('30', '503'),
 ('30', '504'),
 ('30', '505'),
 ('30', '506'),
 ('30', '507'),
 ('30', '508'),
 ('30', '509'),
 ('30', '510'),
 ('30', '511'),
 ('30', '512'),
 ('30', '513'),
 ('30', '514'),
 ('30', '515'),
 ('30', '516'),
 ('30', '517'),
 ('30', '2'),
 ('30', '518'),
 ('30', '519'),
 ('30', '520'),
 ('30', '521'),
 ('30', '522'),
 ('30', '523'),
 ('30', '524'),
 ('30', '525'),
 ('30', '526'),
 ('30', '527'),
 ('30', '528'),
 ('30', '529'),
 ('30', '530'),
 ('30', '531'),
 ('30', '532'),
 ('30', '533'),
 ('30', '534'),
 ('30', '535'),
 ('30', '536'),
 ('30', '537'),
 ('30', '538'),
 ('30', '539'),
 ('30', '540'),
 ('30', '541'),
 ('30', '542'),
 ('30', '543'),
 ('30', '544'),
 ('30', '545'),
 ('30', '546'),
 ('30', '547'),
 ('30', '548'),
 ('30', '549'),
 ('30', '550'),
 ('30', '551'),
 ('30', '552'),
 ('30', '553'),
 ('30', '554'),
 ('30', '555'),
 ('30', '556'),
 ('30', '557'),
 ('30', '558'),
 ('30', '559'),
 ('30', '560'),
 ('30', '561'),
 ('30', '562'),
 ('30', '563'),
 ('30', '564'),
 ('30', '565'),
 ('30', '566'),
 ('30', '567'),
 ('30', '568'),
 ('30', '569'),
 ('30', '570'),
 ('30', '571'),
 ('30', '572'),
 ('30', '573'),
 ('30', '574'),
 ('30', '575'),
 ('30', '576'),
 ('30', '577'),
 ('30', '578'),
 ('30', '579'),
 ('30', '580'),
 ('30', '581'),
 ('30', '582'),
 ('30', '583'),
 ('30', '584'),
 ('30', '585'),
 ('30', '586'),
 ('30', '587'),
 ('30', '588'),
 ('30', '589'),
 ('30', '590'),
 ('30', '591'),
 ('30', '592'),
 ('30', '593'),
 ('30', '594'),
 ('30', '595'),
 ('30', '596'),
 ('30', '597'),
 ('30', '598'),
 ('30', '599'),
 ('30', '600'),
 ('30', '601'),
 ('30', '602'),
 ('30', '603'),
 ('30', '604'),
 ('30', '605'),
 ('30', '606'),
 ('30', '607'),
 ('30', '608'),
 ('30', '609'),
 ('30', '610'),
 ('30', '611'),
 ('30', '612'),
 ('30', '613'),
 ('30', '614'),
 ('30', '615'),
 ('30', '616'),
 ('30', '617'),
 ('30', '618'),
 ('30', '619'),
 ('30', '620'),
 ('30', '621'),
 ('30', '622'),
 ('30', '623'),
 ('30', '624'),
 ('30', '625'),
 ('30', '626'),
 ('30', '627'),
 ('30', '628'),
 ('30', '629'),
 ('30', '630'),
 ('30', '631'),
 ('30', '632'),
 ('30', '633'),
 ('30', '634'),
 ('30', '635'),
 ('30', '636'),
 ('30', '637'),
 ('30', '638'),
 ('30', '639'),
 ('30', '640'),
 ('30', '641'),
 ('30', '642'),
 ('30', '643'),
 ('30', '644'),
 ('30', '645'),
 ('30', '646'),
 ('30', '647'),
 ('30', '648'),
 ('30', '649'),
 ('30', '650'),
 ('30', '651'),
 ('30', '652'),
 ('30', '653'),
 ('30', '654'),
 ('30', '655'),
 ('30', '656'),
 ('30', '657'),
 ('30', '658'),
 ('30', '659'),
 ('30', '660'),
 ('30', '661'),
 ('30', '662'),
 ('30', '663'),
 ('30', '664'),
 ('30', '665'),
 ('30', '666'),
 ('30', '667'),
 ('30', '668'),
 ('30', '669'),
 ('30', '670'),
 ('30', '671'),
 ('30', '672'),
 ('30', '673'),
 ('30', '674'),
 ('30', '675'),
 ('30', '676'),
 ('30', '677'),
 ('30', '678'),
 ('30', '679'),
 ('30', '680'),
 ('30', '681'),
 ('30', '682'),
 ('30', '683'),
 ('30', '684'),
 ('30', '685'),
 ('30', '686'),
 ('30', '687'),
 ('30', '688'),
 ('30', '689'),
 ('30', '690'),
 ('30', '691'),
 ('30', '692'),
 ('30', '693'),
 ('30', '694'),
 ('30', '695'),
 ('30', '696'),
 ('30', '697'),
 ('30', '698'),
 ('30', '699'),
 ('30', '700'),
 ('30', '701'),
 ('30', '702'),
 ('30', '703'),
 ('30', '704'),
 ('30', '12'),
 ('30', '705'),
 ('30', '706'),
 ('30', '707'),
 ('30', '708'),
 ('30', '709'),
 ('30', '710'),
 ('30', '711'),
 ('30', '712'),
 ('30', '713'),
 ('30', '714'),
 ('30', '715'),
 ('30', '716'),
 ('30', '717'),
 ('30', '718'),
 ('30', '719'),
 ('30', '720'),
 ('30', '19'),
 ('30', '721'),
 ('30', '722'),
 ('30', '723'),
 ('30', '724'),
 ('30', '725'),
 ('30', '726'),
 ('30', '727'),
 ('30', '728'),
 ('30', '729'),
 ('30', '730'),
 ('30', '731'),
 ('30', '732'),
 ('30', '733'),
 ('30', '734'),
 ('30', '735'),
 ('30', '736'),
 ('30', '737'),
 ('30', '738'),
 ('30', '739'),
 ('30', '740'),
 ('30', '741'),
 ('30', '742'),
 ('30', '743'),
 ('30', '744'),
 ('30', '745'),
 ('30', '746'),
 ('30', '9'),
 ('30', '747'),
 ('30', '748'),
 ('30', '749'),
 ('30', '750'),
 ('30', '751'),
 ('30', '752'),
 ('30', '753'),
 ('30', '754'),
 ('30', '755'),
 ('30', '756'),
 ('30', '757'),
 ('30', '758'),
 ('30', '759'),
 ('30', '760'),
 ('30', '761'),
 ('30', '762'),
 ('30', '763'),
 ('30', '764'),
 ('30', '765'),
 ('30', '766'),
 ('30', '767'),
 ('30', '768'),
 ('30', '769'),
 ('30', '770'),
 ('30', '771'),
 ('30', '772'),
 ('30', '773'),
 ('30', '774'),
 ('30', '775'),
 ('30', '776'),
 ('30', '777'),
 ('30', '778'),
 ('30', '779'),
 ('30', '780'),
 ('30', '781'),
 ('30', '782'),
 ('30', '783'),
 ('30', '784'),
 ('30', '785'),
 ('30', '786'),
 ('30', '787'),
 ('30', '788'),
 ('30', '789'),
 ('30', '790'),
 ('30', '791'),
 ('30', '792'),
 ('30', '793'),
 ('30', '794'),
 ('30', '795'),
 ('30', '796'),
 ('30', '797'),
 ('30', '798'),
 ('30', '799'),
 ('30', '800'),
 ('30', '801'),
 ('30', '802'),
 ('30', '803'),
 ('30', '804'),
 ('30', '805'),
 ('30', '806'),
 ('30', '807'),
 ('30', '808'),
 ('30', '809'),
 ('30', '810'),
 ('30', '811'),
 ('30', '812'),
 ('30', '0'),
 ('30', '813'),
 ('30', '814'),
 ('30', '815'),
 ('30', '816'),
 ('30', '817'),
 ('30', '22'),
 ('30', '818'),
 ('30', '819'),
 ('30', '820'),
 ('30', '821'),
 ('30', '822'),
 ('30', '823'),
 ('30', '824'),
 ('30', '825'),
 ('30', '826'),
 ('30', '827'),
 ('30', '828'),
 ('30', '829'),
 ('30', '830'),
 ('30', '831'),
 ('30', '832'),
 ('30', '833'),
 ('30', '834'),
 ('30', '835'),
 ('30', '836'),
 ('30', '837'),
 ('30', '838'),
 ('30', '839'),
 ('30', '840'),
 ('30', '841'),
 ('30', '842'),
 ('30', '843'),
 ('30', '844'),
 ('30', '845'),
 ('30', '846'),
 ('30', '847'),
 ('30', '848'),
 ('30', '849'),
 ('30', '850'),
 ('30', '851'),
 ('30', '852'),
 ('30', '853'),
 ('30', '854'),
 ('30', '855'),
 ('30', '856'),
 ('30', '857'),
 ('30', '858'),
 ('30', '859'),
 ('30', '860'),
 ('30', '861'),
 ('30', '862'),
 ('30', '863'),
 ('30', '864'),
 ('30', '865'),
 ('30', '866'),
 ('30', '867'),
 ('30', '868'),
 ('30', '869'),
 ('30', '870'),
 ('30', '871'),
 ('30', '872'),
 ('30', '873'),
 ('30', '874'),
 ('30', '875'),
 ('30', '876'),
 ('30', '877'),
 ('30', '878'),
 ('30', '879'),
 ('30', '880'),
 ('30', '881'),
 ('30', '882'),
 ('30', '883'),
 ('30', '884'),
 ('30', '885'),
 ('30', '886'),
 ('30', '887'),
 ('30', '888'),
 ('30', '889'),
 ('30', '890'),
 ('30', '891'),
 ('30', '892'),
 ('30', '893'),
 ('30', '894'),
 ('30', '895'),
 ('30', '896'),
 ('30', '897'),
 ('30', '898'),
 ('30', '899'),
 ('30', '900'),
 ('30', '901'),
 ('30', '902'),
 ('30', '903'),
 ('30', '904'),
 ('30', '905'),
 ('30', '906'),
 ('30', '907'),
 ('30', '908'),
 ('30', '909'),
 ('30', '910'),
 ('30', '911'),
 ('30', '912'),
 ('30', '913'),
 ('30', '914'),
 ('30', '915'),
 ('30', '916'),
 ('30', '917'),
 ('30', '918'),
 ('30', '919'),
 ('30', '920'),
 ('30', '921'),
 ('30', '922'),
 ('30', '923'),
 ('30', '924'),
 ('30', '925'),
 ('30', '926'),
 ('30', '927'),
 ('30', '928'),
 ('30', '929'),
 ('30', '930'),
 ('30', '931'),
 ('30', '932'),
 ('30', '933'),
 ('30', '934'),
 ('30', '935'),
 ('30', '936'),
 ('30', '937'),
 ('30', '938'),
 ('30', '939'),
 ('30', '940'),
 ('30', '941'),
 ('30', '942'),
 ('30', '943'),
 ('30', '944'),
 ('30', '945'),
 ('30', '946'),
 ('30', '947'),
 ('30', '948'),
 ('30', '949'),
 ('30', '950'),
 ('30', '951'),
 ('30', '952'),
 ('30', '953'),
 ('30', '954'),
 ('30', '955'),
 ('30', '956'),
 ('30', '957'),
 ('30', '958'),
 ('30', '959'),
 ('30', '960'),
 ('30', '961'),
 ('30', '962'),
 ('30', '963'),
 ('30', '964'),
 ('30', '965'),
 ('30', '966'),
 ('30', '967'),
 ('30', '25'),
 ('30', '968'),
 ('30', '969'),
 ('30', '970'),
 ('30', '971'),
 ('30', '972'),
 ('30', '973'),
 ('30', '974'),
 ('30', '975'),
 ('30', '976'),
 ('30', '977'),
 ('30', '978'),
 ('30', '979'),
 ('30', '980'),
 ('30', '981'),
 ('30', '982'),
 ('30', '983'),
 ('30', '984'),
 ('30', '985'),
 ('30', '986'),
 ('30', '987'),
 ('30', '988'),
 ('30', '989'),
 ('30', '990'),
 ('30', '991'),
 ('30', '992'),
 ('30', '993'),
 ('30', '994'),
 ('30', '995'),
 ('30', '996'),
 ('30', '997'),
 ('30', '998'),
 ('30', '999'),
 ('30', '1000'),
 ('30', '1001'),
 ('30', '1002'),
 ('30', '1003'),
 ('30', '1004'),
 ('30', '1005'),
 ('30', '1006'),
 ('30', '1007'),
 ('30', '1008'),
 ('30', '1009'),
 ('30', '1010'),
 ('30', '1011'),
 ('30', '1012'),
 ('30', '1013'),
 ('30', '1014'),
 ('30', '1015'),
 ('30', '1016'),
 ...]

In [10]:
dataframe=pd.DataFrame()
dataframe['names']=superset